---
- name: Copy the smokeping_prober systemd service file
  template:
    src: smokeping_prober.service.j2
    dest: /etc/systemd/system/smokeping_prober.service
    owner: root
    group: root
    mode: 0644
  notify: restart smokeping_prober
